export POSTGRES_HOST=${POSTGRES_HOST:-database}
export POSTGRES_PORT=${POSTGRES_PORT:-5432}
export POSTGRES_USER=${POSTGRES_USER:-hermod}
export POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-hermod}
export POSTGRES_DB=${POSTGRES_DB:-hermod}
export LOG_PATH