<?php

namespace AppBundle\Repository;

use Doctrine\ORM\Query\Expr;
use AppBundle\Entity\Elevator;

/**
 * ElevatorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ElevatorRepository extends \Doctrine\ORM\EntityRepository
{
    public function findOrCreate(string $code, string $source) : Elevator {
        $stopPoint = $this->findOneBy(['code' => $code, 'sourceName' => $source]);

        return is_null($stopPoint) ? new Elevator() : $stopPoint;
    }
}
