<?php

namespace AppBundle\Repository;

use Doctrine\ORM\Query\Expr;

/**
 * LocationPatchRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LocationPatchRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByPeriod(int $day) : array
    {
        $equipment = 'AppBundle\Entity\StopPoint';
        $date = date("Y-m-d",strtotime('-' . $day . ' day'));
        $qb = $this->createQueryBuilder('lp');
        $query = $qb
            ->select('lp, u, e.name AS equipment_name, e.code AS equipment_code, e.sourceName AS equipment_source_name')
            ->from($equipment, 'e')
            ->where($qb->expr()->gt('lp.createdAt', ':date'))
            ->andWhere($qb->expr()->eq('lp.equipmentId', 'e.id'))
            ->join('lp.user', 'u', Expr\Join::WITH, $qb->expr()->eq('u.id', 'lp.user'))
            ->orderBy('lp.createdAt', 'DESC')
            ->setParameter('date', $date)
            ->getQuery()
        ;

        return $query->getResult();
    }
}
