<?php

namespace AppBundle\Repository;

use AppBundle\Entity\StopPoint;

/**
 * StopPointRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StopPointRepository extends \Doctrine\ORM\EntityRepository
{
    public function findOrCreate(string $code, string $source) : StopPoint {
        $stopPoint = $this->findOneBy(['code' => $code, 'sourceName' => $source]);

        return is_null($stopPoint) ? new StopPoint() : $stopPoint;
    }
}
