<?php

namespace AppBundle\Repository;

/**
 * StopPointRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StopPointRepository extends \Doctrine\ORM\EntityRepository
{
}
